name: flet_hyper_effects
description: Flet FletHyperEffects control
repository: https://github.com/MyGithubAccount/flet-hyper-effects/src/flutter/flet_hyper_effects
version: 0.1.0
homepage: https://github.com/MyGithubAccount/flet-hyper-effects

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: 0.27.6
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  hyper_effects: ^0.3.0
  smooth_page_indicator: ^1.2.1
  unicode_emojis: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
